import {Inter} from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {ListActionProvider} from "@/contexts/listActionContext";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <div className="container py-2">
            <Header />
            <ListActionProvider>
                <main style={{minHeight: "71vh"}}>
                    {children}
                </main>
            </ListActionProvider>
            <Footer/>
        </div>
        </body>
        </html>
    );
}
